/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Course: typeof import('./src/components/course/index.vue')['default']
    Find: typeof import('./src/components/find/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Recommend: typeof import('./src/components/recommend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualList: typeof import('./src/components/virtual-list/index.vue')['default']
  }
}
